# Stage Environment Configuration
replicaCount: 2

image:
  repository: ghcr.io/malik-hamza2/two-tier-flask
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"

environment: stage
