apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-chart.fullname" . }}-config
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }}
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  APP_NAME: {{ .Chart.Name | quote }}
